# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Optimization configuration

---
n_epoch: 100
main_args:
    lr: 0.0008
    opt_args: [0.9, 0.999, 0]
    schedule_args: ['step', 20, 0.5]
aux_args:
    lr: 0.005
    opt_args: [0.9, 0.999, 0]
    schedule_args: ['step', 20, 0.5]
loss_args:
    loss: cd_canonical
    xyz_loss_type: cd_l1max
    xyz_subset_weight: 1
    alpha: 1
    beta: 1
clip_max_norm: -1
