# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Configure the Ford dataset as 2D images by spherical projection

dataset: ford_spherical

# Options on spherical coordinate conversion
spherical_cfg:
    height: 128
    width: 2048
    v_fov: [-28, 3.0]
    h_fov: [-180, 180]
    origin_shift: [-0.1, 0.0, -0.4]
    # origin_shift: [0.0, 0.0, 0.0]

# Options on the splitting scheme
splitting:
    train:
        - 1
    val:
        - 2
        - 3
    test:
        - 2
        - 3

# Options under individual configurations
train_cfg:
    batch_size: 4
    shuffle: True
    num_workers: 4
    augmentation: True
    split: train
val_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 4
    augmentation: True
    split: val
test_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 4
    augmentation: False
    split: test