# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Configure the Qnxadas dataset as the octree representation

# Common options of the dataset
dataset: qnxadas_octree
rw_octree: False
rw_partition_scheme: default
translate: [131072, 131072, 131072]
scale: 1
max_num_points: 32000

# Options about octree partitioning
octree_cfg:
    bbox_min: [0, 0, 0]
    bbox_max: [262143, 262143, 262143]
    point_min: 64 # marked as skip if points in a block less than this number
    point_max: 2048 # keep splitting if points in a block larger than this number
    level_min: 3
    level_max: 10

# Options on the splitting scheme
splitting:
    train:
        - qnxadas-motorway-join
        - qnxadas-navigating-bends
    test:
        - qnxadas-junction-approach
        - qnxadas-junction-exit

# Options under individual configurations
train_cfg:
    batch_size: 4
    shuffle: True
    num_workers: 8
    augmentation: True
    split: train
val_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 4
    augmentation: True
    split: val
test_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 4
    augmentation: False
    split: test

