# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Configure the Qnxadas dataset as 2D images by spherical projection

dataset: qnxadas_spherical

# Options on spherical coordinate conversion
spherical_cfg:
    height: 128
    width: 1024
    v_fov: [-20, 24.0]
    h_fov: [-180, 180]
    origin_shift: [0.0, 0.0, 0.0]
    # origin_shift: [-0.1, 0.0, -0.4]

# Options on the splitting scheme
splitting:
    train:
        - qnxadas-motorway-join
        - qnxadas-navigating-bends
    test:
        - qnxadas-junction-approach
        - qnxadas-junction-exit

# Options under individual configurations
train_cfg:
    batch_size: 8
    shuffle: True
    num_workers: 4
    augmentation: True
    split: train
test_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 2
    augmentation: False
    split: test