# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Configure the Qnxadas dataset to load raw 3D points

# Common options of the dataset
dataset: qnxadas_simple
num_points: 80000
seed: 0
return_intensity: False

# Options on the splitting scheme
splitting:
    train:
        - qnxadas-motorway-join
        - qnxadas-navigating-bends
    test:
        - qnxadas-junction-approach
        - qnxadas-junction-exit

# Options under individual configurations
train_cfg:
    batch_size: 8
    shuffle: True
    num_workers: 4
    augmentation: True
    split: train
test_cfg:
    batch_size: 4
    shuffle: False
    num_workers: 2
    augmentation: False
    split: test